# Generated by Django 2.0.2 on 2018-04-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_blogtable_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='tagline',
            field=models.TextField(default='dummy tagline'),
            preserve_default=False,
        ),
    ]
