# Generated by Django 2.0.2 on 2018-04-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogtable_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BlogTable',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
