# Generated by Django 2.0.2 on 2018-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180411_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
